# Generated by Django 5.0 on 2024-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('cource', models.CharField(max_length=55)),
                ('place', models.CharField(max_length=55)),
            ],
        ),
    ]
